JupyterHub installation updates
ioos/Cloud-Sandbox pull request #39
Opened 2023-03-22 17:56 UTC by jonmjoyce

Updated the scripts and instructions to configure JupyterHub on a new machine. These commands were performed on Centos Stream 9. 

- Changed to install conda first, then run jupyterhub from conda
- Improved security by running JupyterHub on a system account (jupyter) instead of root
- Use sudospawner to improve security of users logging into system; prevents users from gaining root access
- Added instructions for creating new conda environments for users. Installed nb_conda_kernels to detect new kernels

2023-03-22 20:08 UTC, patrick-tripp requested changes

2023-03-22 20:08 UTC, patrick-tripp commented on .gitignore
** matches any directory. * matches anything except "/", so this is not a typo. although we don't currently have anything covered by an NDA that needs to be hidden, let's keep the original. please revert and recommit. thanks.

2023-03-22 21:52 UTC, jonmjoyce commented on .gitignore
I was having problems with Git noticing my changes when I first got started. Changing that line fixed it. I just tried again with the line back to the original and my changes are being found correctly, so no issue changing it back.

2023-03-24 15:09 UTC, patrick-tripp approved these changes

2023-03-24 15:10 UTC, merged