Update resource to require token for metric endpoint
ioos/Cloud-Sandbox pull request #52
Opened 2023-05-30 17:24 UTC by ZacharyWills

2023-06-07 19:33 UTC, mwengren commented
@ZacharyWills There are some merge conflicts with this currently.  Would you mind rebasing and resubmitting after #54 can be merged, hopefully?

2023-06-29 21:20 UTC, ZacharyWills commented
@mwengren Give it another look and let me know if it's ready to merge.

2023-07-06 15:26 UTC, mwengren commented
@ZacharyWills My preference would be to keep merge commits out of PRs, if possible.  It will make for a cleaner project history.  

I think you could reapply your changes in the original three commits by running something like

```
git rebase -i main
```

from your feature branch to rewind and then reapply them from the head of the `main` branch.  You might even be able to skip the `-i` flag in this case and apply them directly without editing the commit history interactively.

Then just do a force push to the same branch on your remote and it should clean things up a bit in this PR.  

I don't see any issues with the changes, but to be honest, I don't really have the bandwidth to test them so we'll have to test on the next time we redeploy.

If @patrick-tripp or @jonmjoyce don't see any issues, we can merge this once you've updated the branch I think.

2023-07-06 21:36 UTC, jonmjoyce reviewed
Most of these changes are changes in spacing/formatting so it's difficult to see what the actual code changes were. But the few I found looked fine without testing.

2023-07-06 21:36 UTC, jonmjoyce commented on terraform/main.tf
>    }
This will reassign network_interface_id; should line 377/378 be deleted?

2023-07-07 16:34 UTC, mwengren commented on terraform/main.tf
>    }
Looks like this was introduced in the most recent merge commit af85bfaf9e976a30ae35d341b690a909f1d896ff.  Probably the two added lines should just be removed.

2023-07-07 18:08 UTC, patrick-tripp commented on terraform/main.tf
>    }
Yes, remove the two added lines (those are the from the previous version). EFA isn't needed on the head node.

2023-07-07 18:09 UTC, patrick-tripp approved these changes

2023-07-07 18:11 UTC, patrick-tripp requested changes
Remove the two added lines in main.tf as discussed.

2023-07-10 18:28 UTC, ZacharyWills commented on terraform/main.tf
>    }
Removed these lines, not sure if we still needed the `device_index` line at all.

Take a look.

2023-07-10 19:09 UTC, patrick-tripp approved these changes

2023-07-10 19:10 UTC, merged

2023-07-10 19:21 UTC, ocefpaf commented on terraform/main.tf
> +>>>>>>> 7185af3 (Update resource to require token for metric endpoint)
I'm not a terraform expert but this looks like a git bad merge, no?

2023-07-10 20:19 UTC, patrick-tripp commented on terraform/main.tf
> +>>>>>>> 7185af3 (Update resource to require token for metric endpoint)
Thanks Felipe. It should be ok now.

2023-07-10 20:25 UTC, ocefpaf commented on terraform/main.tf
> +>>>>>>> 7185af3 (Update resource to require token for metric endpoint)
Fixed in https://github.com/ioos/Cloud-Sandbox/pull/61